//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinics
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDRecordList
    {
        public int IDRecordList1 { get; set; }
        public int IDDoctor { get; set; }
        public System.TimeSpan Time { get; set; }
        public System.DateTime Date { get; set; }
        public int IDSpeciality { get; set; }
        public int IDCabinet { get; set; }
    
        public virtual Cabinet Cabinet { get; set; }
        public virtual Specialty Specialty { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
