//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinics
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescript
    {
        public int IDPrescript { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
        public string Medicine { get; set; }
        public Nullable<int> IDDoctor { get; set; }
        public Nullable<int> IDCard { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
