//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinics
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int IDRecord { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> IDCabinet { get; set; }
        public Nullable<int> IDDoctor { get; set; }
        public Nullable<int> IDCard { get; set; }
    
        public virtual Cabinet Cabinet { get; set; }
        public virtual Card Card { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
